(ns app-kotoba-cloud.site-copy
  "Locale catalogs for the public kotoba.cloud pages. One key contract;
  routes are / for English and /{locale}/ for every other language.")

(def supported-locales [:en :ja :hi :ta :zh-Hans :ar :uk :es :fr])

(defn- locale-paths
  [locale]
  (if (= locale :en)
    {:path "/" :legal-path "/legal/" :tokushoho-path "/legal/tokushoho/"}
    (let [root (str "/" (name locale) "/")]
      {:path root
       :legal-path (str root "legal/")
       :tokushoho-path (str root "legal/tokushoho/")})))

(defn- planes
  [storage compute agent]
  [{:kind "STORAGE" :name "Kotobase" :origin "kotobase.net"
    :href "https://kotobase.net"
    :connect-href "https://auth.kotoba.cloud/connect?target=kotobase"
    :body storage}
   {:kind "COMPUTE" :name "Murakumo" :origin "murakumo.cloud"
    :href "https://murakumo.cloud"
    :connect-href "https://auth.kotoba.cloud/connect?target=murakumo"
    :body compute}
   {:kind "AGENT WORK" :name "Itonami" :origin "itonami.cloud"
    :href "https://itonami.cloud"
    :connect-href "https://auth.kotoba.cloud/connect?target=itonami"
    :body agent}])

(def shared
  {:hero-eyebrow "CONTROLLED EXECUTION"
   :control-kind "CONTROL + IDENTITY"
   :control-title "Kotoba Cloud"
   :footer "Kotoba Cloud — identity and deploy control"
   :footer-roles "Language: kotoba-lang.org · Storage: kotobase.net · Compute: murakumo.cloud · Agent work: itonami.cloud"
   :entity-label "法人情報"
   :representative-label "代表者"
   :address-label "所在地"
   :phone-label "電話番号"
   :tokushoho-note "法人情報、代表者、所在地、電話番号は、請求があった場合、法令に従い遅滞なく開示します。"
   :draft false
   :review-banner ""
   :dir "ltr"})

(def ja-existing
  {:html-lang "ja" :og-locale "ja_JP" :hreflang "ja" :language-name "日本語"
   :title "Kotoba Cloud — AIが書くソフトウェアを、制御された実行へ。"
   :description "Kotobaの安全なコードとKotobaseのグラフ状態を、identityとdeploy controlで実行環境へつなぎます。Discoveryは公開中。Hosted applyは未提供です。"
   :skip "本文へ移動" :home-label "Kotoba Cloud ホーム"
   :nav-architecture "構成" :nav-libraries "ライブラリ公開" :nav-label "主要ナビゲーション"
   :language-label "表示言語"
   :headline "AIが書くソフトウェアを、制御された実行へ。"
   :lead ["Kotoba Cloud は、AI が書くソフトウェアの実行環境へつながる identity と deploy control の入口です。Kotoba が言語、Kotobase が信頼できるグラフ状態を担います。"
          "安全なコード。信頼できる状態。制御された実行。Kotoba Labs は、この三つをつなぐ安全で超高速なソフトウェアスタックを目指しています。"]
   :philosophy "他者の達成を助けるとして、Kotoba Cloud は、すでに存在する場所へ人や end user を含む他者がサインインし work を向けるための扉です。"
   :passkey-cta "Base Account で始める" :cli-cta "Kotoba CLI を見る"
   :nav-sign-in "ログイン"
   :live "Discovery と Passkey RP は稼働中。Hosted apply はまだ提供していません。"
   :passkey-fact "ログインと「Base Account で始める」は有償プランではなく、購入でもありません。"
   :authority-fact "ログインは無制限のデプロイ権限ではありません。library publish と CLI deploy は既定で dry-run です。"
   :package-fact "reference-package の install は verified とは主張していません。"
   :rail-fact "有償の payment rail はありません。/.well-known/x402 は 404 です。catalog seller はなく、価格もありません。x402.nexus で支払うことはできません。"
   :identity-label "ログイン中の Identity"
   :signed-in-action "Identity を確認"
   :signed-in-status "ログイン済みの session を確認しました"
   :operator-lead "kotoba.cloud の公開運営元は Kotoba Labs Inc です。"
   :architecture-title "境界を保ったまま、三つの実行面へ。"
   :architecture-lead "一つの巨大な trust domain にまとめず、それぞれの authority を分けたまま接続します。"
   :control-body "Passkey で Stable Principal を確認し、CLI deploy が参照する topology と authority floor を公開します。"
   :connect-label "同じPrincipalで接続"
   :planes (planes
            "AI の状態と知識を支える content-addressed graph database。関係と履歴を明示する。"
            "Admit 済みの workload を CPU/GPU へ配置し、実行する。"
            "Agent の workspace、goal、tool、approval と継続作業を扱う。")
   :library-title "一つのrelease CIDを、複数の保存先から実行する"
   :library-lead "release CIDはnamespace head、definition、raw Wasm、compile receipt、再現性evidenceを一つのIPLD graphに固定します。名前とGitHubは発見・provenanceです。"
   :library-status "耐量子署名は任意ではありません。公開にはPasskey sessionとPrincipalに固定したML-DSA-65署名の両方が必要です。外部Passkey authenticatorと分散認定は別に検証します。"
   :approval-title "ライブラリ公開を承認"
   :approval-lead "CLIがローカル鍵で署名し、Kotobaseへ保存したgraphです。次のCIDとIPNS名を確認してから公開してください。"
   :approval-button "Passkey + ML-DSA-65で公開"
   :key-approval-title "耐量子公開鍵の変更を承認"
   :key-approval-lead "action、epoch、現行鍵と次の鍵を確認してください。ローテーションは両方のML-DSA鍵で署名済みです。Passkey確認後にのみ反映します。"
   :key-approval-button "Passkeyで鍵変更を確定"
   :library-catalog-cta "ライブラリcatalogと依存graphを見る"
   :library-steps [["Bundle" "definition、Wasm artifact、compile receiptを一つのrelease CIDへ閉じる。"]
                   ["Replicate" "同じclosureを少なくとも2つの独立storage originへ保存する。"]
                   ["Verify + Run" "全byteとrouted peer IDを検証し、release CIDとexportから実行する。"]]
   :deploy-title "AIのコードが、許可済みの計算になるまで"
   :steps [["Write" "AIと人間は、読みやすいデータとしてコードを自由に書く。"]
           ["Admit" "Kotobaがtype、effect、capability、resource、targetを検査する。"]
           ["Bind" "Passkey identityと対象限定grantを、host/providerが具体的なscopeへ結びつける。"]
           ["Run" "Kotobaseがartifactとreceiptを保持し、MurakumoとItonamiが許可された処理を担う。"]]
   :boundary-title "境界があるから、つながれる。"
   :boundary-heading "Discoveryは権限委譲ではありません"
   :boundary-p1 "kotoba.cloud は各 origin を発見可能にしますが、storage、compute、agent work を一つの trust domain にしません。receipt は各 origin を別々に記録します。"
   :boundary-p2 "既存の auth.kotobase.net Passkey も自動移行しません。新しい RP では、検証された Principal link が必要です。"
   :profile-link "Machine-readable profile" :spec-link "言語仕様を読む"
   :operator-label "運営元"
   :contact-label "連絡先"
   :legal-link "運営"
   :tokushoho-link "特定商取引法に基づく表記"
   :legal-title "運営元 — Kotoba Cloud"
   :legal-heading "運営元"
   :legal-about "Kotoba Cloud は identity と deploy control の公開入口です。storage、compute、agent work は別 origin のまま接続します。"
   :service-provider-label "役務提供事業者"
   :service-label "対象役務"
   :price-label "販売価格"
   :other-costs-label "価格以外に必要な費用"
   :payment-label "支払方法"
   :payment-timing-label "支払時期"
   :provision-label "役務の提供時期"
   :term-label "契約期間"
   :cancel-label "解約"
   :refund-label "返金"
   :tokushoho-title "特定商取引法に基づく表記 — Kotoba Cloud"
   :tokushoho-heading "特定商取引法に基づく表記"
   :tokushoho-updated "最終更新日: 2026-08-30"
   :tokushoho-service "kotoba.cloud の identity および deploy control（Discovery と Passkey RP）。Hosted apply は提供していません。"
   :tokushoho-price "有償の hosted apply は提供していないため、販売価格はありません。"
   :tokushoho-other-costs "インターネット接続料金その他の通信費はお客様のご負担となります。"
   :tokushoho-payment "有償役務は現在提供していません。"
   :tokushoho-payment-timing "該当なし"
   :tokushoho-provision "Discovery と Passkey RP は公開中です。Hosted apply は提供していません。"
   :tokushoho-term "有償契約はありません。"
   :tokushoho-cancel "該当なし"
   :tokushoho-refund "該当なし"
   :not-found-title "見つかりません — Kotoba Cloud"
   :not-found-heading "その入口はありません。"
   :not-found-lead "Kotoba Cloud の公開入口へ戻ってください。"
   :not-found-cta "kotoba.cloud へ戻る"})

(def en-existing
  {:html-lang "en" :og-locale "en_US" :hreflang "en" :language-name "English"
   :title "Kotoba Cloud — controlled execution for AI-generated software"
   :description "Connect Kotoba code and Kotobase graph state to the execution environment through identity and deploy control. Discovery is live; hosted apply is not yet offered."
   :skip "Skip to content" :home-label "Kotoba Cloud home"
   :nav-architecture "Architecture" :nav-libraries "Publish libraries" :nav-label "Primary navigation"
   :language-label "Display language"
   :headline "Controlled execution for AI-generated software."
   :lead ["Kotoba Cloud is the identity and deploy-control entrance to the execution environment for AI-generated software. Kotoba is the language. Kotobase is the trusted graph state layer."
          "Safe code. Trusted state. Controlled execution. Kotoba Labs is building toward a safe and ultra-fast software stack that connects all three."]
   :philosophy "As 他者の達成を助ける, Kotoba Cloud is the door so another person, including an end user, can sign in and point work at a place that already exists."
   :passkey-cta "Start with a Base Account" :cli-cta "Explore the Kotoba CLI"
   :nav-sign-in "Sign in"
   :live "Discovery and the Passkey RP are live. Hosted apply is not available yet."
   :passkey-fact "Sign in and Start with a Base Account are not a paid plan and not a purchase."
   :authority-fact "A login is not blanket deployment authority. Library publish and CLI deploy are dry-run by default."
   :package-fact "The reference-package install is not claimed verified."
   :rail-fact "There is no paid rail. /.well-known/x402 is 404. There is no catalog seller and no price. Buyers cannot pay on x402.nexus."
   :identity-label "Signed-in identity"
   :signed-in-action "View identity"
   :signed-in-status "Signed-in session confirmed"
   :operator-lead "The public operator of kotoba.cloud is Kotoba Labs Inc."
   :architecture-title "Three execution planes. Boundaries intact."
   :architecture-lead "The services connect without becoming one giant trust domain. Each authority remains separately governed."
   :control-body "Passkey verifies a Stable Principal. The control plane publishes the topology and authority floor used by CLI deploy."
   :connect-label "Connect this Principal"
   :planes (planes
            "A content-addressed graph database for AI state and knowledge, with explicit relationships and identifiable history."
            "Places admitted workloads on CPU/GPU resources and executes them."
            "Runs continuing agent work across workspaces, goals, tools, and approvals.")
   :library-title "One release CID, executable from multiple providers"
   :library-lead "A release CID fixes the namespace head, definitions, raw Wasm, compile receipts, and reproducibility evidence in one IPLD graph. Names and GitHub remain discovery and provenance."
   :library-status "Post-quantum signatures are mandatory, not optional. Publication requires both a Passkey session and an ML-DSA-65 signature pinned to the Principal. External authenticators and distributed qualification remain separately verified boundaries."
   :approval-title "Approve library publication"
   :approval-lead "The CLI signed this graph locally and stored it in Kotobase. Verify the CIDs and IPNS name before publishing."
   :approval-button "Publish with Passkey + ML-DSA-65"
   :key-approval-title "Approve post-quantum key transition"
   :key-approval-lead "Verify the action, epoch, current key, and next key. Rotation is signed by both ML-DSA keys and takes effect only after Passkey confirmation."
   :key-approval-button "Confirm key transition with Passkey"
   :library-catalog-cta "Open the library catalog and dependency graph"
   :library-steps [["Bundle" "Close definitions, Wasm artifacts, and compile receipts under one release CID."]
                   ["Replicate" "Store the same complete closure at no fewer than two independent storage origins."]
                   ["Verify + Run" "Verify every byte and routed peer IDs, then execute by release CID and export."]]
   :deploy-title "From AI-written code to admitted computation"
   :steps [["Write" "Agents and humans write freely in readable, data-oriented code."]
           ["Admit" "Kotoba checks types, effects, capabilities, resources, and target support."]
           ["Bind" "The host and provider bind Passkey identity and a resource-scoped grant."]
           ["Run" "Kotobase keeps artifacts and receipts; Murakumo and Itonami perform the admitted work."]]
   :boundary-title "Boundaries make connection possible."
   :boundary-heading "Discovery is not delegation"
   :boundary-p1 "kotoba.cloud makes each origin discoverable without merging storage, compute, and agent work into one trust domain. Receipts record every origin separately."
   :boundary-p2 "Existing auth.kotobase.net Passkeys do not migrate automatically. The new RP requires a verified Principal link."
   :profile-link "Machine-readable profile" :spec-link "Read the language specification"
   :operator-label "Operator"
   :contact-label "Contact"
   :legal-link "Operator"
   :tokushoho-link "Specified Commercial Transactions notice"
   :legal-title "Operator — Kotoba Cloud"
   :legal-heading "Operator"
   :legal-about "Kotoba Cloud is the public identity and deploy-control entrance. Storage, compute, and agent work remain separately governed origins."
   :service-provider-label "Service provider"
   :service-label "Service"
   :price-label "Price"
   :other-costs-label "Costs other than the price"
   :payment-label "Payment method"
   :payment-timing-label "Payment timing"
   :provision-label "When the service is provided"
   :term-label "Contract term"
   :cancel-label "Cancellation"
   :refund-label "Refunds"
   :tokushoho-title "Specified Commercial Transactions notice — Kotoba Cloud"
   :tokushoho-heading "Specified Commercial Transactions Act notice"
   :tokushoho-updated "Last updated: 2026-08-30"
   :tokushoho-service "kotoba.cloud identity and deploy control (discovery and the Passkey RP). Hosted apply is not offered."
   :tokushoho-price "No sale price applies. Paid hosted apply is not offered."
   :tokushoho-other-costs "Internet access and other communication charges are the customer's responsibility."
   :tokushoho-payment "No paid service is offered."
   :tokushoho-payment-timing "Not applicable"
   :tokushoho-provision "Discovery and the Passkey RP are live. Hosted apply is not offered."
   :tokushoho-term "There is no paid contract."
   :tokushoho-cancel "Not applicable"
   :tokushoho-refund "Not applicable"
   :not-found-title "Not found — Kotoba Cloud"
   :not-found-heading "That entrance does not exist."
   :not-found-lead "Return to the public Kotoba Cloud entrance."
   :not-found-cta "Return to kotoba.cloud"})

(def hi
  {:html-lang "hi" :og-locale "hi_IN" :hreflang "hi" :language-name "हिन्दी"
   :draft true
   :review-banner "यह हिन्दी पृष्ठ Jun की समीक्षा के लिए ड्राफ्ट है। प्रकाशित नहीं है। Draft for Jun to review. Not published."
   :title "Kotoba Cloud — AI द्वारा लिखे सॉफ़्टवेयर के लिए नियंत्रित निष्पादन"
   :description "Kotoba कोड और Kotobase ग्राफ़ अवस्था को identity और deploy control से निष्पादन वातावरण से जोड़ता है। Discovery चालू है; Hosted apply उपलब्ध नहीं है।"
   :skip "सामग्री पर जाएँ" :home-label "Kotoba Cloud होम"
   :nav-architecture "संरचना" :nav-libraries "लाइब्रेरी प्रकाशन" :nav-label "मुख्य नेविगेशन"
   :language-label "प्रदर्शन भाषा"
   :headline "AI द्वारा लिखे सॉफ़्टवेयर के लिए नियंत्रित निष्पादन।"
   :philosophy "他者の達成を助ける के रूप में, Kotoba Cloud वह द्वार है जिससे कोई अन्य व्यक्ति, end user सहित, साइन इन करके पहले से मौजूद स्थान पर work निर्देशित कर सके।"
   :lead ["Kotoba Cloud, AI द्वारा लिखे सॉफ़्टवेयर के निष्पादन वातावरण का identity और deploy-control प्रवेश द्वार है। Kotoba भाषा है। Kotobase विश्वसनीय ग्राफ़-अवस्था परत है।"
          "सुरक्षित कोड। विश्वसनीय अवस्था। नियंत्रित निष्पादन। Kotoba Labs इन तीनों को जोड़ने वाले सुरक्षित और अत्यंत तेज़ सॉफ़्टवेयर स्टैक की ओर निर्माण कर रहा है।"]
   :passkey-cta "Base Account से शुरू करें" :cli-cta "Kotoba CLI देखें"
   :nav-sign-in "साइन इन"
   :live "Discovery और Passkey RP चालू हैं। Hosted apply अभी उपलब्ध नहीं है।"
   :passkey-fact "साइन इन और Base Account से शुरू करना कोई सशुल्क योजना नहीं है और खरीद नहीं है।"
   :authority-fact "लॉगिन व्यापक परिनियोजन अधिकार नहीं है। library publish और CLI deploy डिफ़ॉल्ट रूप से dry-run हैं।"
   :package-fact "reference-package इंस्टॉल को verified नहीं कहा गया है।"
   :rail-fact "कोई सशुल्क payment rail नहीं है। /.well-known/x402 404 है। कोई catalog seller नहीं है और कोई मूल्य नहीं है। x402.nexus पर भुगतान नहीं किया जा सकता।"
   :identity-label "साइन-इन पहचान"
   :signed-in-action "पहचान देखें"
   :signed-in-status "साइन-इन session की पुष्टि हुई"
   :operator-lead "kotoba.cloud का सार्वजनिक संचालक Kotoba Labs Inc है।"
   :architecture-title "तीन निष्पादन तल। सीमाएँ बनी रहती हैं।"
   :architecture-lead "सेवाएँ जुड़ती हैं, पर एक विशाल trust domain नहीं बनतीं। प्रत्येक authority अलग शासित रहती है।"
   :control-body "Passkey एक Stable Principal की पुष्टि करता है। control plane वही topology और authority floor प्रकाशित करता है जिसका CLI deploy उपयोग करता है।"
   :connect-label "इसी Principal से जोड़ें"
   :planes (planes
            "AI अवस्था और ज्ञान के लिए content-addressed graph database, स्पष्ट संबंधों और पहचाने जाने योग्य इतिहास के साथ।"
            "Admit किए गए workload को CPU/GPU पर रखता है और चलाता है।"
            "workspace, goal, tool और approval पर चलने वाला agent कार्य।")
   :library-title "एक release CID, कई प्रदाताओं से निष्पादन योग्य"
   :library-lead "release CID, namespace head, definition, raw Wasm, compile receipt और reproducibility evidence को एक IPLD graph में बाँधता है। नाम और GitHub खोज व provenance हैं।"
   :library-status "उत्तर-क्वांटम हस्ताक्षर अनिवार्य हैं, वैकल्पिक नहीं। प्रकाशन के लिए Passkey session और Principal पर पिन किया ML-DSA-65 हस्ताक्षर दोनों चाहिए। बाहरी authenticator और वितरित योग्यता अलग सीमाएँ हैं।"
   :approval-title "लाइब्रेरी प्रकाशन स्वीकृत करें"
   :approval-lead "CLI ने इस graph पर स्थानीय रूप से हस्ताक्षर किए और Kotobase में संग्रहीत किया। प्रकाशित करने से पहले CID और IPNS नाम जाँचें।"
   :approval-button "Passkey + ML-DSA-65 से प्रकाशित करें"
   :key-approval-title "उत्तर-क्वांटम कुंजी परिवर्तन स्वीकृत करें"
   :key-approval-lead "action, epoch, वर्तमान कुंजी और अगली कुंजी जाँचें। रोटेशन दोनों ML-DSA कुंजियों से हस्ताक्षरित है और केवल Passkey पुष्टि के बाद प्रभावी होता है।"
   :key-approval-button "Passkey से कुंजी परिवर्तन सुनिश्चित करें"
   :library-catalog-cta "लाइब्रेरी catalog और निर्भरता graph खोलें"
   :library-steps [["Bundle" "definition, Wasm artifact और compile receipt को एक release CID में बंद करें।"]
                   ["Replicate" "वही पूरा closure कम से कम दो स्वतंत्र storage origin पर रखें।"]
                   ["Verify + Run" "प्रत्येक byte और routed peer ID जाँचें, फिर release CID और export से चलाएँ।"]]
   :deploy-title "AI-लिखित कोड से स्वीकृत गणना तक"
   :steps [["Write" "एजेंट और मनुष्य पठनीय, डेटा-उन्मुख कोड स्वतंत्र रूप से लिखते हैं।"]
           ["Admit" "Kotoba type, effect, capability, resource और target समर्थन जाँचता है।"]
           ["Bind" "host और provider Passkey identity और सीमित grant बाँधते हैं।"]
           ["Run" "Kotobase artifact और receipt रखता है; Murakumo और Itonami स्वीकृत कार्य करते हैं।"]]
   :boundary-title "सीमाएँ ही संबंध को संभव बनाती हैं।"
   :boundary-heading "Discovery अधिकार-हस्तांतरण नहीं है"
   :boundary-p1 "kotoba.cloud प्रत्येक origin को खोजने योग्य बनाता है, पर storage, compute और agent work को एक trust domain में नहीं मिलाता। receipt प्रत्येक origin को अलग दर्ज करता है।"
   :boundary-p2 "मौजूदा auth.kotobase.net Passkey अपने आप स्थानांतरित नहीं होते। नए RP को सत्यापित Principal link चाहिए।"
   :profile-link "Machine-readable profile" :spec-link "भाषा विनिर्देश पढ़ें"
   :operator-label "संचालक"
   :contact-label "संपर्क"
   :legal-link "संचालक"
   :tokushoho-link "Specified Commercial Transactions सूचना"
   :legal-title "संचालक — Kotoba Cloud"
   :legal-heading "संचालक"
   :legal-about "Kotoba Cloud सार्वजनिक identity और deploy-control प्रवेश द्वार है। storage, compute और agent work अलग-अलग शासित origin रहते हैं।"
   :service-provider-label "सेवा प्रदाता"
   :service-label "सेवा"
   :price-label "मूल्य"
   :other-costs-label "मूल्य के अतिरिक्त लागत"
   :payment-label "भुगतान विधि"
   :payment-timing-label "भुगतान समय"
   :provision-label "सेवा कब दी जाती है"
   :term-label "अनुबंध अवधि"
   :cancel-label "रद्दीकरण"
   :refund-label "धनवापसी"
   :tokushoho-title "Specified Commercial Transactions सूचना — Kotoba Cloud"
   :tokushoho-heading "Specified Commercial Transactions Act सूचना"
   :tokushoho-updated "अंतिम अद्यतन: 2026-08-30"
   :tokushoho-service "kotoba.cloud identity और deploy control (Discovery और Passkey RP)। Hosted apply नहीं दी जाती।"
   :tokushoho-price "कोई विक्रय मूल्य लागू नहीं। सशुल्क hosted apply नहीं दी जाती।"
   :tokushoho-other-costs "इंटरनेट और अन्य संचार शुल्क ग्राहक के उत्तरदायित्व हैं।"
   :tokushoho-payment "कोई सशुल्क सेवा नहीं दी जाती।"
   :tokushoho-payment-timing "लागू नहीं"
   :tokushoho-provision "Discovery और Passkey RP चालू हैं। Hosted apply नहीं दी जाती।"
   :tokushoho-term "कोई सशुल्क अनुबंध नहीं है।"
   :tokushoho-cancel "लागू नहीं"
   :tokushoho-refund "लागू नहीं"
   :not-found-title "नहीं मिला — Kotoba Cloud"
   :not-found-heading "वह प्रवेश द्वार मौजूद नहीं है।"
   :not-found-lead "सार्वजनिक Kotoba Cloud प्रवेश द्वार पर लौटें।"
   :not-found-cta "kotoba.cloud पर लौटें"})

(def ta
  {:html-lang "ta" :og-locale "ta_IN" :hreflang "ta" :language-name "தமிழ்"
   :title "Kotoba Cloud — AI எழுதும் மென்பொருளுக்கு கட்டுப்படுத்தப்பட்ட இயக்கம்"
   :description "Kotoba குறியீட்டையும் Kotobase வரைபட நிலையையும் identity மற்றும் deploy control வழியாக இயக்கச் சூழலுடன் இணைக்கிறது. Discovery இயங்குகிறது; Hosted apply வழங்கப்படவில்லை."
   :skip "உள்ளடக்கத்திற்கு செல்" :home-label "Kotoba Cloud முகப்பு"
   :nav-architecture "அமைப்பு" :nav-libraries "நூலக வெளியீடு" :nav-label "முதன்மை வழிசெலுத்தல்"
   :language-label "காட்சி மொழி"
   :headline "AI எழுதும் மென்பொருளுக்கு கட்டுப்படுத்தப்பட்ட இயக்கம்."
   :philosophy "他者の達成を助ける என்பதன்படி, Kotoba Cloud என்பது மற்றொரு நபர், end user உட்பட, உள்நுழைந்து ஏற்கனவே உள்ள இடத்திற்கு work ஐ நோக்கிச் சுட்டிக்காட்டும் கதவு."
   :lead ["Kotoba Cloud, AI எழுதும் மென்பொருளின் இயக்கச் சூழலுக்கான identity மற்றும் deploy-control நுழைவாயில். Kotoba மொழி. Kotobase நம்பகமான வரைபட-நிலை அடுக்கு."
          "பாதுகாப்பான குறியீடு. நம்பகமான நிலை. கட்டுப்படுத்தப்பட்ட இயக்கம். Kotoba Labs இம்மூன்றையும் இணைக்கும் பாதுகாப்பான, மிக வேகமான மென்பொருள் அடுக்கை நோக்கி கட்டுகிறது."]
   :passkey-cta "Base Account மூலம் தொடங்கு" :cli-cta "Kotoba CLI ஐ பார்க்க"
   :nav-sign-in "உள்நுழை"
   :live "Discovery மற்றும் Passkey RP இயங்குகின்றன. Hosted apply இன்னும் கிடைக்கவில்லை."
   :passkey-fact "உள்நுழைவும் Base Account மூலம் தொடங்குவதும் கட்டணத் திட்டமல்ல, வாங்கல் அல்ல."
   :authority-fact "உள்நுழைவு முழு deploy அதிகாரம் அல்ல. library publish மற்றும் CLI deploy இயல்பாக dry-run."
   :package-fact "reference-package நிறுவல் verified என்று கூறப்படவில்லை."
   :rail-fact "கட்டண payment rail இல்லை. /.well-known/x402 404. catalog seller இல்லை, விலையும் இல்லை. x402.nexus இல் செலுத்த முடியாது."
   :identity-label "உள்நுழைந்த அடையாளம்"
   :signed-in-action "அடையாளத்தைப் பார்"
   :signed-in-status "உள்நுழைந்த session உறுதிசெய்யப்பட்டது"
   :operator-lead "kotoba.cloud இன் பொது இயக்குநர் Kotoba Labs Inc."
   :architecture-title "மூன்று இயக்கத் தளங்கள். எல்லைகள் அப்படியே."
   :architecture-lead "சேவைகள் இணைகின்றன; ஒரு பெரிய trust domain ஆக இணையவில்லை. ஒவ்வொரு authority-யும் தனி ஆட்சியில் இருக்கிறது."
   :control-body "Passkey ஒரு Stable Principal ஐ உறுதிசெய்கிறது. control plane, CLI deploy பயன்படுத்தும் topology மற்றும் authority floor ஐ வெளியிடுகிறது."
   :connect-label "இந்த Principal உடன் இணை"
   :planes (planes
            "AI நிலை மற்றும் அறிவுக்கான content-addressed graph database; தெளிவான உறவுகளும் அடையாளம் காணக்கூடிய வரலாறும்."
            "Admit செய்யப்பட்ட workload-களை CPU/GPU இல் வைத்து இயக்குகிறது."
            "workspace, goal, tool, approval ஆகியவற்றில் தொடரும் agent பணி.")
   :library-title "ஒரு release CID, பல வழங்குநர்களிலிருந்து இயக்கலாம்"
   :library-lead "release CID, namespace head, definition, raw Wasm, compile receipt, reproducibility evidence ஆகியவற்றை ஒரு IPLD graph இல் நிலைநிறுத்துகிறது. பெயர்களும் GitHub-உம் கண்டுபிடிப்பும் provenance-உம்."
   :library-status "பின்-குவாண்டம் கையொப்பங்கள் கட்டாயம், விருப்பமல்ல. வெளியீட்டுக்கு Passkey session மற்றும் Principal-இல் பதிக்கப்பட்ட ML-DSA-65 கையொப்பம் இரண்டும் வேண்டும். வெளி authenticator மற்றும் பரவலான தகுதி தனி எல்லைகள்."
   :approval-title "நூலக வெளியீட்டை அங்கீகரி"
   :approval-lead "CLI இந்த graph-ஐ உள்ளூரில் கையொப்பமிட்டு Kotobase இல் சேமித்தது. வெளியிடும் முன் CID மற்றும் IPNS பெயரை சரிபார்க்கவும்."
   :approval-button "Passkey + ML-DSA-65 மூலம் வெளியிடு"
   :key-approval-title "பின்-குவாண்டம் விசை மாற்றத்தை அங்கீகரி"
   :key-approval-lead "action, epoch, தற்போதைய விசை, அடுத்த விசை ஆகியவற்றை சரிபார்க்கவும். சுழற்சி இரு ML-DSA விசைகளாலும் கையொப்பமிடப்பட்டு, Passkey உறுதிக்குப் பிறகே நடைமுறைக்கு வரும்."
   :key-approval-button "Passkey மூலம் விசை மாற்றத்தை உறுதிசெய்"
   :library-catalog-cta "நூலக catalog மற்றும் சார்பு graph ஐ திற"
   :library-steps [["Bundle" "definition, Wasm artifact, compile receipt ஆகியவற்றை ஒரு release CID கீழ் மூடு."]
                   ["Replicate" "அதே முழு closure-ஐ குறைந்தது இரண்டு தனி storage origin இல் வை."]
                   ["Verify + Run" "ஒவ்வொரு byte மற்றும் routed peer ID ஐ சரிபார்த்து, release CID மற்றும் export மூலம் இயக்கு."]]
   :deploy-title "AI எழுதிய குறியீட்டிலிருந்து அனுமதிக்கப்பட்ட கணிப்பு வரை"
   :steps [["Write" "முகவர்களும் மனிதர்களும் வாசிக்கக்கூடிய, தரவு-மையக் குறியீட்டை சுதந்திரமாக எழுதுகின்றனர்."]
           ["Admit" "Kotoba type, effect, capability, resource, target ஆதரவை சரிபார்க்கிறது."]
           ["Bind" "host மற்றும் provider Passkey identity மற்றும் வரம்புள்ள grant ஐ பிணைக்கின்றனர்."]
           ["Run" "Kotobase artifact மற்றும் receipt வைத்திருக்கிறது; Murakumo மற்றும் Itonami அனுமதிக்கப்பட்ட பணியைச் செய்கின்றன."]]
   :boundary-title "எல்லைகளே இணைப்பை சாத்தியமாக்குகின்றன."
   :boundary-heading "Discovery அதிகார ஒப்படைப்பு அல்ல"
   :boundary-p1 "kotoba.cloud ஒவ்வொரு origin-ஐயும் கண்டறியச் செய்கிறது; storage, compute, agent work ஐ ஒரு trust domain ஆக இணைப்பதில்லை. receipt ஒவ்வொரு origin-ஐயும் தனியாக பதிவுசெய்கிறது."
   :boundary-p2 "இருக்கும் auth.kotobase.net Passkey தானாக இடம்பெயராது. புதிய RP-க்கு சரிபார்க்கப்பட்ட Principal link வேண்டும்."
   :profile-link "Machine-readable profile" :spec-link "மொழி விவரக்குறிப்பைப் படி"
   :operator-label "இயக்குநர்"
   :contact-label "தொடர்பு"
   :legal-link "இயக்குநர்"
   :tokushoho-link "Specified Commercial Transactions அறிவிப்பு"
   :legal-title "இயக்குநர் — Kotoba Cloud"
   :legal-heading "இயக்குநர்"
   :legal-about "Kotoba Cloud பொது identity மற்றும் deploy-control நுழைவாயில். storage, compute, agent work தனி ஆட்சி origin ஆகவே இருக்கும்."
   :service-provider-label "சேவை வழங்குநர்"
   :service-label "சேவை"
   :price-label "விலை"
   :other-costs-label "விலை தவிர செலவுகள்"
   :payment-label "கட்டண முறை"
   :payment-timing-label "கட்டண நேரம்"
   :provision-label "சேவை எப்போது வழங்கப்படுகிறது"
   :term-label "ஒப்பந்த காலம்"
   :cancel-label "ரத்து"
   :refund-label "திரும்பப்பெறுதல்"
   :tokushoho-title "Specified Commercial Transactions அறிவிப்பு — Kotoba Cloud"
   :tokushoho-heading "Specified Commercial Transactions Act அறிவிப்பு"
   :tokushoho-updated "கடைசியாக புதுப்பிக்கப்பட்டது: 2026-08-30"
   :tokushoho-service "kotoba.cloud identity மற்றும் deploy control (Discovery மற்றும் Passkey RP). Hosted apply வழங்கப்படவில்லை."
   :tokushoho-price "விற்பனை விலை இல்லை. கட்டண hosted apply வழங்கப்படவில்லை."
   :tokushoho-other-costs "இணையம் மற்றும் பிற தகவல் தொடர்பு கட்டணங்கள் வாடிக்கையாளர் பொறுப்பு."
   :tokushoho-payment "கட்டண சேவை வழங்கப்படவில்லை."
   :tokushoho-payment-timing "பொருந்தாது"
   :tokushoho-provision "Discovery மற்றும் Passkey RP இயங்குகின்றன. Hosted apply வழங்கப்படவில்லை."
   :tokushoho-term "கட்டண ஒப்பந்தம் இல்லை."
   :tokushoho-cancel "பொருந்தாது"
   :tokushoho-refund "பொருந்தாது"
   :not-found-title "காணவில்லை — Kotoba Cloud"
   :not-found-heading "அந்த நுழைவாயில் இல்லை."
   :not-found-lead "பொது Kotoba Cloud நுழைவாயிலுக்குத் திரும்பவும்."
   :not-found-cta "kotoba.cloud க்குத் திரும்பு"})

(def zh-Hans
  {:html-lang "zh-Hans" :og-locale "zh_CN" :hreflang "zh-Hans" :language-name "简体中文"
   :title "Kotoba Cloud — 面向 AI 生成软件的受控执行"
   :description "通过 identity 与 deploy control，将 Kotoba 代码和 Kotobase 图状态接入执行环境。Discovery 已上线；Hosted apply 尚未提供。"
   :skip "跳到正文" :home-label "Kotoba Cloud 首页"
   :nav-architecture "架构" :nav-libraries "发布库" :nav-label "主导航"
   :language-label "显示语言"
   :headline "面向 AI 生成软件的受控执行。"
   :philosophy "作为他者の達成を助ける，Kotoba Cloud 是一扇门，好让另一个人（包括 end user）登录并把 work 指向一个已经存在的地方。"
   :lead ["Kotoba Cloud 是 AI 生成软件进入执行环境的 identity 与 deploy-control 入口。Kotoba 是语言。Kotobase 是可信图状态层。"
          "安全的代码。可信的状态。受控的执行。Kotoba Labs 正在建设连接这三者的安全且超高速软件栈。"]
   :passkey-cta "用 Base Account 开始" :cli-cta "查看 Kotoba CLI"
   :nav-sign-in "登录"
   :live "Discovery 与 Passkey RP 已上线。Hosted apply 尚不可用。"
   :passkey-fact "登录和「用 Base Account 开始」不是付费方案，也不是购买。"
   :authority-fact "登录并不等于全面部署权限。library publish 与 CLI deploy 默认 dry-run。"
   :package-fact "不声称 reference-package 安装已经 verified。"
   :rail-fact "没有付费 payment rail。/.well-known/x402 为 404。没有 catalog seller，也没有价格。无法在 x402.nexus 付款。"
   :identity-label "已登录身份"
   :signed-in-action "查看身份"
   :signed-in-status "已确认登录 session"
   :operator-lead "kotoba.cloud 的公开运营方是 Kotoba Labs Inc。"
   :architecture-title "三个执行面。边界保持不变。"
   :architecture-lead "各服务相互连接，但不会合成一个巨大的 trust domain。每项 authority 仍单独治理。"
   :control-body "Passkey 验证 Stable Principal。control plane 公布 CLI deploy 所使用的 topology 与 authority floor。"
   :connect-label "用此 Principal 连接"
   :planes (planes
            "面向 AI 状态与知识的 content-addressed graph database，关系明确，历史可识别。"
            "将已 Admit 的 workload 放到 CPU/GPU 上并执行。"
            "在 workspace、goal、tool 与 approval 上继续 agent 工作。")
   :library-title "一个 release CID，可从多个存储方执行"
   :library-lead "release CID 把 namespace head、definition、raw Wasm、compile receipt 与 reproducibility evidence 固定在一个 IPLD graph 中。名称与 GitHub 仍是发现与 provenance。"
   :library-status "后量子签名是强制的，不是可选项。发布需要 Passkey session 以及固定到 Principal 的 ML-DSA-65 签名。外部 authenticator 与分布式认定仍是单独边界。"
   :approval-title "批准库发布"
   :approval-lead "CLI 已在本地签名此 graph 并写入 Kotobase。发布前请核验 CID 与 IPNS 名称。"
   :approval-button "用 Passkey + ML-DSA-65 发布"
   :key-approval-title "批准后量子密钥变更"
   :key-approval-lead "请核验 action、epoch、当前密钥与下一密钥。轮换已由两把 ML-DSA 密钥签名，仅在 Passkey 确认后生效。"
   :key-approval-button "用 Passkey 确认密钥变更"
   :library-catalog-cta "打开库 catalog 与依赖 graph"
   :library-steps [["Bundle" "将 definition、Wasm artifact 与 compile receipt 收束到一个 release CID。"]
                   ["Replicate" "把同一完整 closure 存到不少于两个独立 storage origin。"]
                   ["Verify + Run" "核验每一字节与 routed peer ID，再按 release CID 与 export 执行。"]]
   :deploy-title "从 AI 所写代码到被允许的计算"
   :steps [["Write" "智能体与人用可读、面向数据的代码自由书写。"]
           ["Admit" "Kotoba 检查 type、effect、capability、resource 与 target 支持。"]
           ["Bind" "host 与 provider 绑定 Passkey identity 与限定范围的 grant。"]
           ["Run" "Kotobase 保存 artifact 与 receipt；Murakumo 与 Itonami 执行被允许的工作。"]]
   :boundary-title "有边界，才能连接。"
   :boundary-heading "Discovery 不是授权委托"
   :boundary-p1 "kotoba.cloud 让各 origin 可被发现，但不会把 storage、compute 与 agent work 并成一个 trust domain。receipt 分别记录每个 origin。"
   :boundary-p2 "现有 auth.kotobase.net Passkey 不会自动迁移。新的 RP 需要经过验证的 Principal link。"
   :profile-link "Machine-readable profile" :spec-link "阅读语言规范"
   :operator-label "运营方"
   :contact-label "联系"
   :legal-link "运营方"
   :tokushoho-link "特定商交易法相关公示"
   :legal-title "运营方 — Kotoba Cloud"
   :legal-heading "运营方"
   :legal-about "Kotoba Cloud 是公开的 identity 与 deploy-control 入口。storage、compute 与 agent work 仍是分开治理的 origin。"
   :service-provider-label "服务提供方"
   :service-label "服务"
   :price-label "价格"
   :other-costs-label "价格以外的费用"
   :payment-label "支付方式"
   :payment-timing-label "支付时间"
   :provision-label "服务提供时间"
   :term-label "合同期限"
   :cancel-label "取消"
   :refund-label "退款"
   :tokushoho-title "特定商交易法相关公示 — Kotoba Cloud"
   :tokushoho-heading "特定商交易法相关公示"
   :tokushoho-updated "最后更新日期：2026-08-30"
   :tokushoho-service "kotoba.cloud 的 identity 与 deploy control（Discovery 与 Passkey RP）。不提供 Hosted apply。"
   :tokushoho-price "不适用销售价格。不提供付费 hosted apply。"
   :tokushoho-other-costs "互联网接入及其他通信费用由客户承担。"
   :tokushoho-payment "不提供付费服务。"
   :tokushoho-payment-timing "不适用"
   :tokushoho-provision "Discovery 与 Passkey RP 已上线。不提供 Hosted apply。"
   :tokushoho-term "没有付费合同。"
   :tokushoho-cancel "不适用"
   :tokushoho-refund "不适用"
   :not-found-title "未找到 — Kotoba Cloud"
   :not-found-heading "没有那个入口。"
   :not-found-lead "请返回公开的 Kotoba Cloud 入口。"
   :not-found-cta "返回 kotoba.cloud"})

(def ar
  {:html-lang "ar" :og-locale "ar_001" :hreflang "ar" :language-name "العربية"
   :dir "rtl"
   :draft true
   :review-banner "هذه الصفحة العربية مسودة لمراجعة Jun وليست منشورة. Draft for Jun to review. Not published."
   :title "Kotoba Cloud — تنفيذ مضبوط للبرمجيات التي يولّدها الذكاء الاصطناعي"
   :description "يربط شفرة Kotoba وحالة الرسم البياني في Kotobase ببيئة التنفيذ عبر identity وdeploy control. Discovery يعمل؛ Hosted apply غير مقدَّم."
   :skip "انتقل إلى المحتوى" :home-label "الصفحة الرئيسة لـ Kotoba Cloud"
   :nav-architecture "البنية" :nav-libraries "نشر المكتبات" :nav-label "التنقل الرئيسي"
   :language-label "لغة العرض"
   :headline "تنفيذ مضبوط للبرمجيات التي يولّدها الذكاء الاصطناعي."
   :philosophy "بوصفها 他者の達成を助ける، Kotoba Cloud هو الباب حتى يتمكن شخص آخر، بما في ذلك end user، من تسجيل الدخول وتوجيه work إلى مكان موجود مسبقاً."
   :lead ["Kotoba Cloud هو مدخل identity وdeploy-control إلى بيئة تنفيذ البرمجيات التي يولّدها الذكاء الاصطناعي. Kotoba هي اللغة. Kotobase طبقة حالة الرسم البياني الموثوقة."
          "شفرة آمنة. حالة موثوقة. تنفيذ مضبوط. تعمل Kotoba Labs نحو رزمة برمجيات آمنة وسريعة جداً تصل بين الثلاثة."]
   :passkey-cta "ابدأ بـ Base Account" :cli-cta "اطّلع على Kotoba CLI"
   :nav-sign-in "تسجيل الدخول"
   :live "Discovery وPasskey RP يعملان. Hosted apply غير متاح بعد."
   :passkey-fact "تسجيل الدخول و«ابدأ بـ Base Account» ليسا خطة مدفوعة وليسا عملية شراء."
   :authority-fact "تسجيل الدخول ليس سلطة نشر شاملة. library publish وCLI deploy يعملان dry-run افتراضياً."
   :package-fact "لا يُدّعى أن تثبيت reference-package تم التحقق منه (verified)."
   :rail-fact "لا توجد سكة دفع مدفوعة. /.well-known/x402 يعيد 404. لا يوجد catalog seller ولا سعر. لا يمكن الدفع على x402.nexus."
   :identity-label "هوية الجلسة"
   :signed-in-action "عرض الهوية"
   :signed-in-status "تم تأكيد session مسجّلة الدخول"
   :operator-lead "المشغّل العلني لـ kotoba.cloud هو Kotoba Labs Inc."
   :architecture-title "ثلاثة سطوح تنفيذ. الحدود قائمة."
   :architecture-lead "تتصل الخدمات دون أن تصبح نطاق ثقة واحداً ضخماً. تبقى كل authority محكومة على حدة."
   :control-body "يثبّت Passkey هوية Stable Principal. تنشر control plane الطوبولوجيا وauthority floor التي يستخدمها CLI deploy."
   :connect-label "اربط هذا Principal"
   :planes (planes
            "قاعدة بيانات رسم بياني معنون بالمحتوى لحالة الذكاء الاصطناعي ومعرفته، بعلاقات صريحة وتاريخ قابل للتعرّف."
            "يضع أحمال العمل المقبولة (Admit) على CPU/GPU وينفّذها."
            "يدير عمل الوكيل المستمر عبر workspace وgoal وtool وapproval.")
   :library-title "release CID واحد قابل للتنفيذ من عدة مزوّدين"
   :library-lead "يثبّت release CID رأس namespace والتعريفات وraw Wasm وإيصالات التجميع وأدلة إعادة الإنتاج في رسم IPLD واحد. تبقى الأسماء وGitHub للاكتشاف وprovenance."
   :library-status "التوقيعات ما بعد الكمّ إلزامية وليست اختيارية. النشر يتطلّب session Passkey وتوقيع ML-DSA-65 مثبتاً على Principal. تبقى المصادقات الخارجية والتأهيل الموزّع حدوداً منفصلة."
   :approval-title "اعتماد نشر المكتبة"
   :approval-lead "وقّعت CLI هذا الرسم محلياً وخزّنته في Kotobase. تحقق من CID واسم IPNS قبل النشر."
   :approval-button "انشر بـ Passkey + ML-DSA-65"
   :key-approval-title "اعتماد انتقال مفتاح ما بعد الكمّ"
   :key-approval-lead "تحقق من action وepoch والمفتاح الحالي والمفتاح التالي. التدوير موقّع بمفتاحَي ML-DSA ولا يسري إلا بعد تأكيد Passkey."
   :key-approval-button "أكّد انتقال المفتاح بـ Passkey"
   :library-catalog-cta "افتح catalog المكتبات ورسم الاعتماد"
   :library-steps [["Bundle" "اجمع التعريفات وWasm وcompile receipt تحت release CID واحد."]
                   ["Replicate" "اخزن نفس الـ closure الكامل في أصلَي تخزين مستقلين على الأقل."]
                   ["Verify + Run" "تحقق من كل بايت ومعرّفات peer الموجّهة، ثم نفّذ حسب release CID وexport."]]
   :deploy-title "من شفرة يكتبها الذكاء الاصطناعي إلى حساب مقبول"
   :steps [["Write" "يكتب الوكلاء والبشر بحرية شفرة مقروءة موجّهة للبيانات."]
           ["Admit" "يفحص Kotoba الأنواع والآثار والقدرات والموارد ودعم الهدف."]
           ["Bind" "يربط المضيف والمزوّد هوية Passkey ومنحة محدودة النطاق."]
           ["Run" "يحتفظ Kotobase بالقطع والإيصالات؛ ينفّذ Murakumo وItonami العمل المقبول."]]
   :boundary-title "الحدود تجعل الاتصال ممكناً."
   :boundary-heading "Discovery ليس تفويضاً"
   :boundary-p1 "يجعل kotoba.cloud كل origin قابلاً للاكتشاف دون دمج التخزين والحساب وعمل الوكيل في نطاق ثقة واحد. تسجّل الإيصالات كل origin على حدة."
   :boundary-p2 "لا تنتقل مفاتيح Passkey الحالية على auth.kotobase.net تلقائياً. يتطلّب RP الجديد رابط Principal متحققاً منه."
   :profile-link "Machine-readable profile" :spec-link "اقرأ مواصفة اللغة"
   :operator-label "المشغّل"
   :contact-label "الاتصال"
   :legal-link "المشغّل"
   :tokushoho-link "إشعار المعاملات التجارية المحددة"
   :legal-title "المشغّل — Kotoba Cloud"
   :legal-heading "المشغّل"
   :legal-about "Kotoba Cloud هو المدخل العلني لـ identity وdeploy control. يبقى التخزين والحساب وعمل الوكيل أصولاً محكومة على حدة."
   :service-provider-label "مقدّم الخدمة"
   :service-label "الخدمة"
   :price-label "السعر"
   :other-costs-label "تكاليف غير السعر"
   :payment-label "طريقة الدفع"
   :payment-timing-label "توقيت الدفع"
   :provision-label "متى تُقدَّم الخدمة"
   :term-label "مدة العقد"
   :cancel-label "الإلغاء"
   :refund-label "الاسترداد"
   :tokushoho-title "إشعار المعاملات التجارية المحددة — Kotoba Cloud"
   :tokushoho-heading "إشعار قانون المعاملات التجارية المحددة"
   :tokushoho-updated "آخر تحديث: 2026-08-30"
   :tokushoho-service "identity وdeploy control على kotoba.cloud (Discovery وPasskey RP). Hosted apply غير مقدَّم."
   :tokushoho-price "لا ينطبق سعر بيع. لا يُقدَّم hosted apply مدفوع."
   :tokushoho-other-costs "رسوم الإنترنت والاتصال الأخرى على مسؤولية العميل."
   :tokushoho-payment "لا تُقدَّم خدمة مدفوعة."
   :tokushoho-payment-timing "لا ينطبق"
   :tokushoho-provision "Discovery وPasskey RP يعملان. Hosted apply غير مقدَّم."
   :tokushoho-term "لا يوجد عقد مدفوع."
   :tokushoho-cancel "لا ينطبق"
   :tokushoho-refund "لا ينطبق"
   :not-found-title "غير موجود — Kotoba Cloud"
   :not-found-heading "ذلك المدخل غير موجود."
   :not-found-lead "عد إلى مدخل Kotoba Cloud العلني."
   :not-found-cta "العودة إلى kotoba.cloud"})

(def uk
  {:html-lang "uk" :og-locale "uk_UA" :hreflang "uk" :language-name "Українська"
   :title "Kotoba Cloud — контрольоване виконання програм, які пише ШІ"
   :description "З’єднує код Kotoba і графовий стан Kotobase із середовищем виконання через identity і deploy control. Discovery працює; Hosted apply не пропонується."
   :skip "Перейти до змісту" :home-label "Домівка Kotoba Cloud"
   :nav-architecture "Архітектура" :nav-libraries "Публікація бібліотек" :nav-label "Основна навігація"
   :language-label "Мова відображення"
   :headline "Контрольоване виконання програм, які пише ШІ."
   :philosophy "Як 他者の達成を助ける, Kotoba Cloud — це двері, щоб інша людина, зокрема end user, могла увійти й спрямувати work на місце, яке вже існує."
   :lead ["Kotoba Cloud — це вхід identity і deploy-control до середовища виконання програм, які пише ШІ. Kotoba — мова. Kotobase — шар довіреного графового стану."
          "Безпечний код. Довірений стан. Контрольоване виконання. Kotoba Labs будує безпечний і надшвидкий програмний стек, що з’єднує всі три."]
   :passkey-cta "Почати з Base Account" :cli-cta "Переглянути Kotoba CLI"
   :nav-sign-in "Увійти"
   :live "Discovery і Passkey RP працюють. Hosted apply ще недоступний."
   :passkey-fact "Вхід і «Почати з Base Account» — не платний план і не покупка."
   :authority-fact "Вхід не дає повної влади на розгортання. library publish і CLI deploy за замовчуванням dry-run."
   :package-fact "Встановлення reference-package не заявлено як verified."
   :rail-fact "Платної payment rail немає. /.well-known/x402 повертає 404. Немає catalog seller і немає ціни. Платити на x402.nexus не можна."
   :identity-label "Ідентичність після входу"
   :signed-in-action "Переглянути ідентичність"
   :signed-in-status "Підтверджено session після входу"
   :operator-lead "Публічний оператор kotoba.cloud — Kotoba Labs Inc."
   :architecture-title "Три площини виконання. Межі збережено."
   :architecture-lead "Сервіси з’єднуються, не стаючи однією великою trust domain. Кожна authority лишається окремо керованою."
   :control-body "Passkey підтверджує Stable Principal. control plane публікує topology і authority floor, якими користується CLI deploy."
   :connect-label "Під’єднати цей Principal"
   :planes (planes
            "Адресована за вмістом графова база для стану й знань ШІ з явними зв’язками та пізнаваною історією."
            "Розміщує допущені (Admit) навантаження на CPU/GPU і виконує їх."
            "Веде тривалу agent-роботу в workspace, goal, tool і approval.")
   :library-title "Один release CID, виконуваний з кількох сховищ"
   :library-lead "release CID фіксує namespace head, definition, raw Wasm, compile receipt і reproducibility evidence в одному IPLD graph. Імена та GitHub лишаються відкриттям і provenance."
   :library-status "Постквантові підписи обов’язкові, не опційні. Для публікації потрібні Passkey session і підпис ML-DSA-65, прив’язаний до Principal. Зовнішні authenticator і розподілена кваліфікація — окремі межі."
   :approval-title "Схвалити публікацію бібліотеки"
   :approval-lead "CLI підписала цей graph локально й зберегла в Kotobase. Перевірте CID та ім’я IPNS перед публікацією."
   :approval-button "Опублікувати через Passkey + ML-DSA-65"
   :key-approval-title "Схвалити зміну постквантового ключа"
   :key-approval-lead "Перевірте action, epoch, поточний і наступний ключ. Ротацію підписано обома ключами ML-DSA; вона набирає чинності лише після підтвердження Passkey."
   :key-approval-button "Підтвердити зміну ключа через Passkey"
   :library-catalog-cta "Відкрити catalog бібліотек і граф залежностей"
   :library-steps [["Bundle" "Зібрати definition, Wasm artifact і compile receipt під одним release CID."]
                   ["Replicate" "Зберегти той самий повний closure щонайменше на двох незалежних storage origin."]
                   ["Verify + Run" "Перевірити кожен байт і routed peer ID, тоді виконати за release CID і export."]]
   :deploy-title "Від коду, який пише ШІ, до допущеного обчислення"
   :steps [["Write" "Агенти й люди вільно пишуть читабельний, орієнтований на дані код."]
           ["Admit" "Kotoba перевіряє type, effect, capability, resource і підтримку target."]
           ["Bind" "host і provider прив’язують Passkey identity і обмежений grant."]
           ["Run" "Kotobase зберігає artifact і receipt; Murakumo та Itonami виконують допущене."]]
   :boundary-title "Межі роблять з’єднання можливим."
   :boundary-heading "Discovery — це не делегування"
   :boundary-p1 "kotoba.cloud робить кожен origin видимим, не зливаючи storage, compute і agent work в одну trust domain. receipt фіксує кожен origin окремо."
   :boundary-p2 "Наявні Passkey з auth.kotobase.net не мігрують автоматично. Новий RP потребує перевіреного Principal link."
   :profile-link "Machine-readable profile" :spec-link "Читати специфікацію мови"
   :operator-label "Оператор"
   :contact-label "Контакт"
   :legal-link "Оператор"
   :tokushoho-link "Повідомлення про зазначені комерційні транзакції"
   :legal-title "Оператор — Kotoba Cloud"
   :legal-heading "Оператор"
   :legal-about "Kotoba Cloud — публічний вхід identity і deploy control. storage, compute і agent work лишаються окремо керованими origin."
   :service-provider-label "Постачальник послуги"
   :service-label "Послуга"
   :price-label "Ціна"
   :other-costs-label "Витрати поза ціною"
   :payment-label "Спосіб оплати"
   :payment-timing-label "Строк оплати"
   :provision-label "Коли надається послуга"
   :term-label "Строк договору"
   :cancel-label "Скасування"
   :refund-label "Повернення"
   :tokushoho-title "Повідомлення про зазначені комерційні транзакції — Kotoba Cloud"
   :tokushoho-heading "Повідомлення за законом про зазначені комерційні транзакції"
   :tokushoho-updated "Останнє оновлення: 2026-08-30"
   :tokushoho-service "identity і deploy control kotoba.cloud (Discovery і Passkey RP). Hosted apply не пропонується."
   :tokushoho-price "Ціни продажу немає. Платного hosted apply немає."
   :tokushoho-other-costs "Інтернет та інші витрати на зв’язок несе клієнт."
   :tokushoho-payment "Платної послуги немає."
   :tokushoho-payment-timing "Не застосовується"
   :tokushoho-provision "Discovery і Passkey RP працюють. Hosted apply не пропонується."
   :tokushoho-term "Платного договору немає."
   :tokushoho-cancel "Не застосовується"
   :tokushoho-refund "Не застосовується"
   :not-found-title "Не знайдено — Kotoba Cloud"
   :not-found-heading "Цього входу не існує."
   :not-found-lead "Поверніться до публічного входу Kotoba Cloud."
   :not-found-cta "Повернутися на kotoba.cloud"})

(def es
  {:html-lang "es" :og-locale "es_ES" :hreflang "es" :language-name "Español"
   :title "Kotoba Cloud — ejecución controlada para software generado por IA"
   :description "Conecta el código Kotoba y el estado de grafo de Kotobase al entorno de ejecución mediante identity y deploy control. Discovery está en marcha; Hosted apply no se ofrece."
   :skip "Saltar al contenido" :home-label "Inicio de Kotoba Cloud"
   :nav-architecture "Arquitectura" :nav-libraries "Publicar bibliotecas" :nav-label "Navegación principal"
   :language-label "Idioma de visualización"
   :headline "Ejecución controlada para software generado por IA."
   :philosophy "Como 他者の達成を助ける, Kotoba Cloud es la puerta para que otra persona, incluido un end user, inicie sesión y dirija work a un lugar que ya existe."
   :lead ["Kotoba Cloud es la entrada de identity y deploy-control al entorno de ejecución del software generado por IA. Kotoba es el lenguaje. Kotobase es la capa de estado de grafo de confianza."
          "Código seguro. Estado de confianza. Ejecución controlada. Kotoba Labs construye hacia una pila de software segura y ultrarrápida que conecta las tres."]
   :passkey-cta "Empezar con un Base Account" :cli-cta "Ver la Kotoba CLI"
   :nav-sign-in "Iniciar sesión"
   :live "Discovery y el Passkey RP están en marcha. Hosted apply aún no está disponible."
   :passkey-fact "Iniciar sesión y Empezar con un Base Account no son un plan de pago ni una compra."
   :authority-fact "Un inicio de sesión no es autoridad general de despliegue. library publish y CLI deploy son dry-run por defecto."
   :package-fact "La instalación del reference-package no se declara verified."
   :rail-fact "No hay rail de pago. /.well-known/x402 es 404. No hay catalog seller ni precio. No se puede pagar en x402.nexus."
   :identity-label "Identidad con sesión iniciada"
   :signed-in-action "Ver identidad"
   :signed-in-status "Sesión iniciada confirmada"
   :operator-lead "El operador público de kotoba.cloud es Kotoba Labs Inc."
   :architecture-title "Tres planos de ejecución. Límites intactos."
   :architecture-lead "Los servicios se conectan sin convertirse en un solo trust domain enorme. Cada authority sigue gobernada por separado."
   :control-body "Passkey verifica un Stable Principal. El control plane publica la topology y el authority floor que usa CLI deploy."
   :connect-label "Conectar este Principal"
   :planes (planes
            "Base de datos de grafo direccionada por contenido para estado y conocimiento de IA, con relaciones explícitas e historial identificable."
            "Coloca workloads admitidos en CPU/GPU y los ejecuta."
            "Ejecuta el trabajo continuo de agent en workspace, goal, tool y approval.")
   :library-title "Un release CID, ejecutable desde varios proveedores"
   :library-lead "Un release CID fija el namespace head, las definition, el raw Wasm, los compile receipt y la reproducibility evidence en un IPLD graph. Los nombres y GitHub siguen siendo descubrimiento y provenance."
   :library-status "Las firmas poscuánticas son obligatorias, no opcionales. La publicación exige una Passkey session y una firma ML-DSA-65 fijada al Principal. Los authenticator externos y la cualificación distribuida siguen siendo límites aparte."
   :approval-title "Aprobar la publicación de la biblioteca"
   :approval-lead "La CLI firmó este graph en local y lo guardó en Kotobase. Verifique los CID y el nombre IPNS antes de publicar."
   :approval-button "Publicar con Passkey + ML-DSA-65"
   :key-approval-title "Aprobar el cambio de clave poscuántica"
   :key-approval-lead "Verifique action, epoch, clave actual y siguiente. La rotación está firmada por ambas claves ML-DSA y solo rige tras la confirmación Passkey."
   :key-approval-button "Confirmar el cambio de clave con Passkey"
   :library-catalog-cta "Abrir el catalog de bibliotecas y el grafo de dependencias"
   :library-steps [["Bundle" "Cerrar definition, artefactos Wasm y compile receipt bajo un release CID."]
                   ["Replicate" "Guardar el mismo closure completo en no menos de dos storage origin independientes."]
                   ["Verify + Run" "Verificar cada byte y los peer ID enrutados; ejecutar por release CID y export."]]
   :deploy-title "Del código escrito por IA al cómputo admitido"
   :steps [["Write" "Agentes y humanos escriben con libertad código legible y orientado a datos."]
           ["Admit" "Kotoba comprueba type, effect, capability, resource y el soporte del target."]
           ["Bind" "El host y el provider vinculan la Passkey identity y un grant de alcance limitado."]
           ["Run" "Kotobase guarda artifact y receipt; Murakumo e Itonami realizan el trabajo admitido."]]
   :boundary-title "Los límites hacen posible la conexión."
   :boundary-heading "Discovery no es delegación"
   :boundary-p1 "kotoba.cloud hace descubrible cada origin sin fusionar storage, compute y agent work en un solo trust domain. Los receipt registran cada origin por separado."
   :boundary-p2 "Los Passkey existentes de auth.kotobase.net no migran automáticamente. El nuevo RP exige un Principal link verificado."
   :profile-link "Machine-readable profile" :spec-link "Leer la especificación del lenguaje"
   :operator-label "Operador"
   :contact-label "Contacto"
   :legal-link "Operador"
   :tokushoho-link "Aviso de transacciones comerciales especificadas"
   :legal-title "Operador — Kotoba Cloud"
   :legal-heading "Operador"
   :legal-about "Kotoba Cloud es la entrada pública de identity y deploy control. storage, compute y agent work siguen siendo origin gobernados por separado."
   :service-provider-label "Proveedor del servicio"
   :service-label "Servicio"
   :price-label "Precio"
   :other-costs-label "Costes distintos del precio"
   :payment-label "Método de pago"
   :payment-timing-label "Momento del pago"
   :provision-label "Cuándo se presta el servicio"
   :term-label "Duración del contrato"
   :cancel-label "Cancelación"
   :refund-label "Reembolso"
   :tokushoho-title "Aviso de transacciones comerciales especificadas — Kotoba Cloud"
   :tokushoho-heading "Aviso de la Ley de transacciones comerciales especificadas"
   :tokushoho-updated "Última actualización: 2026-08-30"
   :tokushoho-service "identity y deploy control de kotoba.cloud (Discovery y el Passkey RP). Hosted apply no se ofrece."
   :tokushoho-price "No hay precio de venta. No se ofrece hosted apply de pago."
   :tokushoho-other-costs "El acceso a Internet y demás gastos de comunicación corren a cargo del cliente."
   :tokushoho-payment "No se ofrece un servicio de pago."
   :tokushoho-payment-timing "No aplicable"
   :tokushoho-provision "Discovery y el Passkey RP están en marcha. Hosted apply no se ofrece."
   :tokushoho-term "No hay contrato de pago."
   :tokushoho-cancel "No aplicable"
   :tokushoho-refund "No aplicable"
   :not-found-title "No encontrado — Kotoba Cloud"
   :not-found-heading "Esa entrada no existe."
   :not-found-lead "Vuelva a la entrada pública de Kotoba Cloud."
   :not-found-cta "Volver a kotoba.cloud"})

(def fr
  {:html-lang "fr" :og-locale "fr_FR" :hreflang "fr" :language-name "Français"
   :title "Kotoba Cloud — exécution contrôlée pour les logiciels générés par l’IA"
   :description "Relie le code Kotoba et l’état de graphe Kotobase à l’environnement d’exécution via identity et deploy control. Discovery est en service ; Hosted apply n’est pas proposé."
   :skip "Aller au contenu" :home-label "Accueil Kotoba Cloud"
   :nav-architecture "Architecture" :nav-libraries "Publier des bibliothèques" :nav-label "Navigation principale"
   :language-label "Langue d’affichage"
   :headline "Exécution contrôlée pour les logiciels générés par l’IA."
   :philosophy "En tant que 他者の達成を助ける, Kotoba Cloud est la porte pour qu’une autre personne, y compris un end user, se connecte et oriente le work vers un lieu qui existe déjà."
   :lead ["Kotoba Cloud est l’entrée identity et deploy-control vers l’environnement d’exécution des logiciels générés par l’IA. Kotoba est le langage. Kotobase est la couche d’état de graphe de confiance."
          "Code sûr. État de confiance. Exécution contrôlée. Kotoba Labs construit une pile logicielle sûre et ultra-rapide qui relie les trois."]
   :passkey-cta "Commencer avec un Base Account" :cli-cta "Voir la Kotoba CLI"
   :nav-sign-in "Connexion"
   :live "Discovery et le Passkey RP sont en service. Hosted apply n’est pas encore disponible."
   :passkey-fact "Connexion et Commencer avec un Base Account ne sont ni un forfait payant ni un achat."
   :authority-fact "Une connexion n’est pas une autorité générale de déploiement. library publish et CLI deploy sont en dry-run par défaut."
   :package-fact "L’installation du reference-package n’est pas déclarée verified."
   :rail-fact "Il n’existe pas de rail de paiement. /.well-known/x402 renvoie 404. Il n’y a ni catalog seller ni prix. On ne peut pas payer sur x402.nexus."
   :identity-label "Identité connectée"
   :signed-in-action "Voir l’identité"
   :signed-in-status "Session connectée confirmée"
   :operator-lead "L’opérateur public de kotoba.cloud est Kotoba Labs Inc."
   :architecture-title "Trois plans d’exécution. Frontières intactes."
   :architecture-lead "Les services se connectent sans devenir un seul immense trust domain. Chaque authority reste gouvernée séparément."
   :control-body "Passkey vérifie un Stable Principal. Le control plane publie la topology et l’authority floor utilisées par CLI deploy."
   :connect-label "Connecter ce Principal"
   :planes (planes
            "Base de graphe adressée par le contenu pour l’état et les connaissances de l’IA, avec relations explicites et historique identifiable."
            "Place les workloads admis sur CPU/GPU et les exécute."
            "Poursuit le travail d’agent sur workspace, goal, tool et approval.")
   :library-title "Un release CID, exécutable depuis plusieurs fournisseurs"
   :library-lead "Un release CID fige le namespace head, les definition, le raw Wasm, les compile receipt et la reproducibility evidence dans un IPLD graph. Les noms et GitHub restent découverte et provenance."
   :library-status "Les signatures post-quantiques sont obligatoires, non optionnelles. La publication exige une Passkey session et une signature ML-DSA-65 épinglée au Principal. Les authenticator externes et la qualification distribuée restent des frontières distinctes."
   :approval-title "Approuver la publication de bibliothèque"
   :approval-lead "La CLI a signé ce graph localement et l’a stocké dans Kotobase. Vérifiez les CID et le nom IPNS avant de publier."
   :approval-button "Publier avec Passkey + ML-DSA-65"
   :key-approval-title "Approuver la transition de clé post-quantique"
   :key-approval-lead "Vérifiez action, epoch, clé actuelle et clé suivante. La rotation est signée par les deux clés ML-DSA et ne prend effet qu’après confirmation Passkey."
   :key-approval-button "Confirmer la transition de clé avec Passkey"
   :library-catalog-cta "Ouvrir le catalog des bibliothèques et le graphe de dépendances"
   :library-steps [["Bundle" "Fermer definition, artefacts Wasm et compile receipt sous un release CID."]
                   ["Replicate" "Stocker la même closure complète sur au moins deux storage origin indépendants."]
                   ["Verify + Run" "Vérifier chaque octet et les peer ID routés, puis exécuter par release CID et export."]]
   :deploy-title "Du code écrit par l’IA au calcul admis"
   :steps [["Write" "Agents et humains écrivent librement un code lisible, orienté données."]
           ["Admit" "Kotoba vérifie type, effect, capability, resource et le support de la cible."]
           ["Bind" "L’hôte et le fournisseur lient l’identité Passkey et un grant à portée limitée."]
           ["Run" "Kotobase conserve artifact et receipt ; Murakumo et Itonami exécutent le travail admis."]]
   :boundary-title "Les frontières rendent la connexion possible."
   :boundary-heading "Discovery n’est pas une délégation"
   :boundary-p1 "kotoba.cloud rend chaque origin découvrable sans fusionner storage, compute et agent work en un seul trust domain. Les receipt enregistrent chaque origin séparément."
   :boundary-p2 "Les Passkey existants de auth.kotobase.net ne migrent pas automatiquement. Le nouveau RP exige un Principal link vérifié."
   :profile-link "Machine-readable profile" :spec-link "Lire la spécification du langage"
   :operator-label "Opérateur"
   :contact-label "Contact"
   :legal-link "Opérateur"
   :tokushoho-link "Avis sur les transactions commerciales spécifiées"
   :legal-title "Opérateur — Kotoba Cloud"
   :legal-heading "Opérateur"
   :legal-about "Kotoba Cloud est l’entrée publique identity et deploy control. storage, compute et agent work restent des origin gouvernés séparément."
   :service-provider-label "Prestataire"
   :service-label "Service"
   :price-label "Prix"
   :other-costs-label "Frais autres que le prix"
   :payment-label "Mode de paiement"
   :payment-timing-label "Moment du paiement"
   :provision-label "Quand le service est fourni"
   :term-label "Durée du contrat"
   :cancel-label "Annulation"
   :refund-label "Remboursement"
   :tokushoho-title "Avis sur les transactions commerciales spécifiées — Kotoba Cloud"
   :tokushoho-heading "Avis au titre de la loi sur les transactions commerciales spécifiées"
   :tokushoho-updated "Dernière mise à jour : 2026-08-30"
   :tokushoho-service "identity et deploy control de kotoba.cloud (Discovery et le Passkey RP). Hosted apply n’est pas proposé."
   :tokushoho-price "Aucun prix de vente. Le hosted apply payant n’est pas proposé."
   :tokushoho-other-costs "L’accès Internet et les autres frais de communication sont à la charge du client."
   :tokushoho-payment "Aucun service payant n’est proposé."
   :tokushoho-payment-timing "Sans objet"
   :tokushoho-provision "Discovery et le Passkey RP sont en service. Hosted apply n’est pas proposé."
   :tokushoho-term "Il n’existe pas de contrat payant."
   :tokushoho-cancel "Sans objet"
   :tokushoho-refund "Sans objet"
   :not-found-title "Introuvable — Kotoba Cloud"
   :not-found-heading "Cette entrée n’existe pas."
   :not-found-lead "Revenez à l’entrée publique de Kotoba Cloud."
   :not-found-cta "Retourner sur kotoba.cloud"})

(defn- catalog
  [locale specific]
  (merge shared (locale-paths locale) specific))

(def copy
  {:en (catalog :en en-existing)
   :ja (catalog :ja ja-existing)
   :hi (catalog :hi hi)
   :ta (catalog :ta ta)
   :zh-Hans (catalog :zh-Hans zh-Hans)
   :ar (catalog :ar ar)
   :uk (catalog :uk uk)
   :es (catalog :es es)
   :fr (catalog :fr fr)})

(def published-locales
  (filterv #(not (get-in copy [% :draft])) supported-locales))

(def draft-locales
  (filterv #(get-in copy [% :draft]) supported-locales))
